@startuml
class Main{
+ static void main(String[] args)
}

class Media{
- string title
- string category
- float rating
- int year

}

class Menu{

}

class MainMenu {
    + void searchMedia
    + void searchCategory
    + void watchList
    + void savedContent
}

class StartMenu {
    + void login
    + void createUser

}


class Movie{
}

class Series{
- int episodes
- int seasons
}

class User{
- string username
- string password
}

package "util" {
class TextUI{
- Scanner scanner

+void displayMsg(String s)
+int promptNumeric(String msg)
+String promptText(String msg)
+int promptChoice(String msg, ArrayList<String> list)
+boolean promptBinary(String msg)
}
class FileIO{
+ArrayList<String> readUserData(String path)
+void saveData(ArrayList<User> users, String path)
}
}

Menu *-- Media
Media<|--Series
Media <|-- Movie
Menu *-- User
Main *-- Menu
Menu <|-- MainMenu
Menu <|-- StartMenu




@enduml