@startuml
class Main{
+ static void main(String[] args)
}

class Media{
- String title
- int year
- String category
- float rating
+Media(String title, int year, String category, float rating)


}

class MediaClient{
-String name
-ArrayList<User> users
-User currentUser
-String userDataPath
-ArrayList<String> listOfActions
-TextUI ui
-FileIO io
+Mediaclient(String name)
+void createUser()
+void setup()
+void loadUserData()
+void closeClient()
+void runDialog()


}

class MainMenu {
    + void searchMedia
    + void searchCategory
    + void watchList
    + void savedContent
}

class StartMenu {
    + void login
    + void createUser

}


class Movie{
}

class Series{
- int episodes
- int seasons
+Series(String title, int year, String category, float rating, int episodes)
}

class User{
-String name
-int age
-Account account
}

class Account{
- string username
- string password
}

package "util" {
class TextUI{
- Scanner scanner

+void displayMsg(String s)
+int promptNumeric(String msg)
+String promptText(String msg)
+int promptChoice(String msg, ArrayList<String> list)
+boolean promptBinary(String msg)
}
class FileIO{
+ArrayList<String> readUserData(String path)
+void saveData(ArrayList<User> users, String path)
}
}

MediaClient *-- Media
Media<|--Series
Media <|-- Movie
MediaClient *-- User
Main *-- MediaClient
MediaClient *-- MainMenu
MediaClient *-- StartMenu
MediaClient *-- "util"
User *-- Account




@enduml