@startuml

object MediaClient
object Media
object Series
object Movie
object User
object MediaActions



MediaClient*-- User
MediaClient *-- Media
MediaClient *-- MediaActions
Media <|-- Movie
Media <|-- Series





@enduml