@startuml

object Main
object User
object Media
object Series
object Movie
object Account
object Menu
object StartMenu
object MainMenu


Main*--Media
Main *-- User
Media <|-- Movie
Media <|-- Series
User *-- Account
Main *-- Menu
Menu *-- StartMenu
Menu *-- MainMenu



@enduml