@startuml

object MediaClient
object Media
object Series
object Movie
object Account
object User



MediaClient*-- User
MediaClient *-- Media
Media <|-- Movie
Media <|-- Series
User *-- Account




@enduml